services:
  backend:
    build: .
    image: abrohamovich/littleshop-backend:latest
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: littleshop
      DB_USERNAME: littleshop_user
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SUBPROTOCOL: postgresql
      ADMIN_FIRSTNAME: ${ADMIN_FIRSTNAME}
      ADMIN_LASTNAME: ${ADMIN_LASTNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PHONE: ${ADMIN_PHONE}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JWT_TOKEN: ${JWT_TOKEN}
    depends_on:
      - db
    networks:
      - network

  frontend:
    image: abrohamovich/littleshop-frontend:latest
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - network

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: littleshop
      POSTGRES_USER: littleshop_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - network

volumes:
  data:

networks:
  network: