version: '3.8'

services:
  backend:
    build: .
    image: littleshop-backend:latest
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: littleshop
      DB_USERNAME: littleshop_user
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SUBPROTOCOL: postgresql
    depends_on:
      - db
    networks:
      - network

  frontend:
    build:
      context: ${FRONTEND_PATH}
    image: littleshop-frontend:latest
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - network

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: littleshop
      POSTGRES_USER: littleshop_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - network

volumes:
  data:

networks:
  network: