spring:
  application:
    name: littleshop
  datasource:
    url: jdbc:${DB_SUBPROTOCOL}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
logging:
  level:
    root: INFO
    org.abrohamovich.littleshop: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.abrohamovich.littleshop.infrastructure.aspect: DEBUG

server:
  port: 8080
